%Find the intrinsic parameters of the camera.
clear; 

%Set up the camera
vid1 = imaq.VideoDevice('kinectv2imaq', 1);
preview(vid1);
%Specify the number of images to be used in the calibration
NoOfImage = 30;
%Take the photos of the checkboard
for i = 1:NoOfImage
    image_capture = imresize(fliplr(step(vid1)), [240 450]);  % take camera shot
    filename = strcat('d:\code\Image',int2str(i),'.png')
    imwrite(image_capture,filename)
    pause(0.333333); % wait 1/3 second
end

release(vid1);

% Define images to process
imageFileNames = {'d:\code\Image1.png',...
    'd:\code\Image2.png',...
    'd:\code\Image3.png',...
    'd:\code\Image4.png',...
    'd:\code\Image5.png',...
    'd:\code\Image6.png',...
    'd:\code\Image7.png',...
    'd:\code\Image8.png',...
    'd:\code\Image9.png',...
    'd:\code\Image10.png'...
    'd:\code\Image11.png',...
        'd:\code\Image12.png',...
    'd:\code\Image13.png',...
    'd:\code\Image14.png',...
    'd:\code\Image15.png',...
    'd:\code\Image16.png',...
    'd:\code\Image17.png',...
    'd:\code\Image18.png',...
    'd:\code\Image19.png',...
    'd:\code\Image20.png'...
    'd:\code\Image21.png',...
        'd:\code\Image22.png',...
    'd:\code\Image23.png',...
    'd:\code\Image24.png',...
    'd:\code\Image25.png',...
    'd:\code\Image26.png',...
    'd:\code\Image27.png',...
    'd:\code\Image28.png',...
    'd:\code\Image29.png',...
    'd:\code\Image30.png'...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 15;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

%Save the intrinsic camera parameters
save('d:\code\cal.mat', 'cameraParams', 'worldPoints');